"""answer table

Revision ID: f6cc3ddaa551
Revises: c745aed60ff7
Create Date: 2023-06-14 16:27:32.788891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cc3ddaa551'
down_revision = 'c745aed60ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('A1', sa.String(length=64), nullable=True),
    sa.Column('A2', sa.String(length=64), nullable=True),
    sa.Column('A3', sa.String(length=64), nullable=True),
    sa.Column('A4', sa.String(length=64), nullable=True),
    sa.Column('A5', sa.String(length=64), nullable=True),
    sa.Column('A6', sa.String(length=64), nullable=True),
    sa.Column('A7', sa.String(length=64), nullable=True),
    sa.Column('A8', sa.String(length=64), nullable=True),
    sa.Column('A9', sa.String(length=64), nullable=True),
    sa.Column('A10', sa.String(length=64), nullable=True),
    sa.Column('A11', sa.String(length=64), nullable=True),
    sa.Column('A12', sa.String(length=64), nullable=True),
    sa.Column('A13', sa.String(length=64), nullable=True),
    sa.Column('A14', sa.String(length=64), nullable=True),
    sa.Column('A15', sa.String(length=64), nullable=True),
    sa.Column('A16', sa.String(length=64), nullable=True),
    sa.Column('A17', sa.String(length=64), nullable=True),
    sa.Column('A18', sa.String(length=64), nullable=True),
    sa.Column('A19', sa.String(length=64), nullable=True),
    sa.Column('A20', sa.String(length=64), nullable=True),
    sa.Column('A21', sa.String(length=64), nullable=True),
    sa.Column('A22', sa.String(length=64), nullable=True),
    sa.Column('A23', sa.String(length=64), nullable=True),
    sa.Column('A24', sa.String(length=64), nullable=True),
    sa.Column('A25', sa.String(length=64), nullable=True),
    sa.Column('A26', sa.String(length=64), nullable=True),
    sa.Column('A27', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_timestamp'))

    op.drop_table('answer')
    # ### end Alembic commands ###
